/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package vistas;

/**
 *
 * @author edgar
 */
public class FrmDatosUsuario extends javax.swing.JFrame {

    /** Creates new form DatosUsuario */
    public FrmDatosUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        JcbGenero.addItem("Masculino");
        JcbGenero.addItem("Femenino");
        JcbAlcaldia.addItem("Azcapotzalco");   
        JcbAlcaldia.addItem("Alvaro Obregon");   
        JcbAlcaldia.addItem("Benito Juarez");   
        JcbAlcaldia.addItem("Coyoacan");   
        JcbAlcaldia.addItem("Cuajimalpa de Morelos");   
        JcbAlcaldia.addItem("Cuauhtemoc");   
        JcbAlcaldia.addItem("Gustavo A. Madero");   
        JcbAlcaldia.addItem("Iztacalco");   
        JcbAlcaldia.addItem("Iztapalapa");   
        JcbAlcaldia.addItem("Magdalena Contreras");   
        JcbAlcaldia.addItem("Miguel Hidalgo");   
        JcbAlcaldia.addItem("Milpa Alta");   
        JcbAlcaldia.addItem("Tlalpan");   
        JcbAlcaldia.addItem("Tlahuac");   
        JcbAlcaldia.addItem("Venustiano Carranza");   
        JcbAlcaldia.addItem("Xochimilco");     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtnExit = new javax.swing.JButton();
        JcbAlcaldia = new javax.swing.JComboBox<>();
        txt_nombre = new vistas.JPlaceholderTextField("Nombre");
        txt_edad = new vistas.JPlaceholderTextField("Edad");
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JcbGenero = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos del usuario");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(202, 250, 238));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 680));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1050, 630));
        jPanel2.setMinimumSize(new java.awt.Dimension(1050, 630));
        jPanel2.setPreferredSize(new java.awt.Dimension(1050, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(97, 205, 226));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese los datos que desea modificar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1050, 50));

        jBtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAdmin/ExitLogo.png"))); // NOI18N
        jBtnExit.setBorder(null);
        jBtnExit.setContentAreaFilled(false);
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, -1, -1));

        JcbAlcaldia.setBackground(new java.awt.Color(204, 204, 204));
        JcbAlcaldia.setBorder(null);
        JcbAlcaldia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbAlcaldiaItemStateChanged(evt);
            }
        });
        JcbAlcaldia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbAlcaldiaActionPerformed(evt);
            }
        });
        jPanel2.add(JcbAlcaldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 250, 40));

        txt_nombre.setBorder(null);
        jPanel2.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 480, 30));

        txt_edad.setBorder(null);
        jPanel2.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 480, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/txtNombre1.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/txtNombre1.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        JcbGenero.setBackground(new java.awt.Color(204, 204, 204));
        JcbGenero.setBorder(null);
        JcbGenero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JcbGeneroItemStateChanged(evt);
            }
        });
        JcbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbGeneroActionPerformed(evt);
            }
        });
        jPanel2.add(JcbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 250, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAdmin/DatosUsuariologo.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, -1, -1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 520, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/mc_sup_derecha.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -10, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesAdmin/mc_sup.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 1270, 230));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/mc_derecha.png"))); // NOI18N
        jLabel2.setText(" ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcbGeneroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbGeneroItemStateChanged
        String genero = (String)JcbGenero.getSelectedItem();
    }//GEN-LAST:event_JcbGeneroItemStateChanged

    private void JcbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbGeneroActionPerformed

    private void JcbAlcaldiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JcbAlcaldiaItemStateChanged
        String alcaldia = (String)JcbAlcaldia.getSelectedItem();
    }//GEN-LAST:event_JcbAlcaldiaItemStateChanged

    private void JcbAlcaldiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbAlcaldiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbAlcaldiaActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        FrmAdmin admin = new FrmAdmin();
        admin.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDatosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbAlcaldia;
    private javax.swing.JComboBox<String> JcbGenero;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private vistas.JPlaceholderTextField txt_edad;
    private vistas.JPlaceholderTextField txt_nombre;
    // End of variables declaration//GEN-END:variables

}
