/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class FrmVistaDatos extends javax.swing.JFrame {
    /**
     * Creates new form FrmVistaDatos
     */
    public FrmVistaDatos() {
        initComponents();
        FrmDatosPrenda datos = new FrmDatosPrenda();

        this.setLocationRelativeTo(null);
//modelo.removeRow(modelo.getRowCount()-1); eliminar una fila
/*
int filas = modelo.getRowCount();
for (int i = 1; i <= filas; i++){
modelo.removeRow(0);
}
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextPrenda = new javax.swing.JTextField();
        jTextTela = new javax.swing.JTextField();
        jTextCantidad = new javax.swing.JTextField();
        jTextTalla = new javax.swing.JTextField();
        jTextPrendaPantalon = new javax.swing.JTextField();
        jTextTelaPantalon = new javax.swing.JTextField();
        jTextTallaPantalon = new javax.swing.JTextField();
        jTextCantidadPantalon = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(202, 250, 238));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 680));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1150, 630));
        jPanel2.setPreferredSize(new java.awt.Dimension(1150, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextPrenda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPrenda.setText(" Prenda");
        jPanel1.add(jTextPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 235, 30));

        jTextTela.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTela.setText("Tipo de tela");
        jTextTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 0, 235, 30));

        jTextCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCantidad.setText("Cantidad");
        jPanel1.add(jTextCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 0, 235, 30));

        jTextTalla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTalla.setText("Talla");
        jTextTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTallaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 235, 30));

        jTextPrendaPantalon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPrendaPantalon.setText("Pantalon");
        jPanel1.add(jTextPrendaPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 235, 30));

        jTextTelaPantalon.setEditable(false);
        jTextTelaPantalon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTelaPantalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelaPantalonActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTelaPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 30, 235, 30));

        jTextTallaPantalon.setEditable(false);
        jTextTallaPantalon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTallaPantalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTallaPantalonActionPerformed(evt);
            }
        });
        jPanel1.add(jTextTallaPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 235, 30));

        jTextCantidadPantalon.setEditable(false);
        jTextCantidadPantalon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextCantidadPantalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 30, 235, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 940, 310));

        panel1.setBackground(new java.awt.Color(96, 204, 225));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("seguro de que son correctos.");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1038, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Estos son los datos ingresados, seleccione calcular si está");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1038, -1));

        jPanel2.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1050, 80));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesUser/btnCalcular.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesUser/btnEditar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/base_b.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/mc_sup_derecha.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/line_b.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/line_t.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/image (1).png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrmResultados resultados = new FrmResultados();
        resultados.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmDatosPrenda datos = new FrmDatosPrenda();
        datos.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTallaActionPerformed

    private void jTextTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelaActionPerformed

    private void jTextTelaPantalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelaPantalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelaPantalonActionPerformed

    private void jTextTallaPantalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTallaPantalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTallaPantalonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JTextField jTextCantidad;
    public static javax.swing.JTextField jTextCantidadPantalon;
    public static javax.swing.JTextField jTextPrenda;
    public static javax.swing.JTextField jTextPrendaPantalon;
    public static javax.swing.JTextField jTextTalla;
    public static javax.swing.JTextField jTextTallaPantalon;
    public static javax.swing.JTextField jTextTela;
    public static javax.swing.JTextField jTextTelaPantalon;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
